spring.application.name=order-service
server.port=8082

spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# In Docker Compose this is overridden to http://product-service:8081
product-service.base-url=http://localhost:8081

management.endpoints.web.exposure.include=health
